--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.688.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2022. 01. 29. 19:17:54
-- Server version: 10.4.22
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS project;

CREATE DATABASE project
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

--
-- Set default database
--
USE project;

--
-- Create table `user`
--
CREATE TABLE user (
  id INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) DEFAULT NULL,
  fullname VARCHAR(255) DEFAULT NULL,
  profile_img_url VARCHAR(255) DEFAULT NULL,
  favorite_categories ENUM('category_id') DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create index `favorite_categories` on table `user`
--
ALTER TABLE user 
  ADD UNIQUE INDEX favorite_categories(favorite_categories);

--
-- Create table `uploaded_music`
--
CREATE TABLE uploaded_music (
  id INT(11) NOT NULL AUTO_INCREMENT,
  alkoto_id INT(11) DEFAULT NULL,
  alkotas_fuggetlen VARCHAR(255) DEFAULT NULL,
  embed VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create index `alkoto_id` on table `uploaded_music`
--
ALTER TABLE uploaded_music 
  ADD UNIQUE INDEX alkoto_id(alkoto_id);

--
-- Create table `music`
--
CREATE TABLE music (
  id INT(11) NOT NULL AUTO_INCREMENT,
  alkoto_id INT(11) DEFAULT NULL,
  alkotas_adat VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create index `alkoto_id` on table `music`
--
ALTER TABLE music 
  ADD UNIQUE INDEX alkoto_id(alkoto_id);

--
-- Create table `liked_post`
--
CREATE TABLE liked_post (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user_id INT(11) DEFAULT NULL,
  music_id INT(11) DEFAULT NULL,
  date DATE DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create index `user_id` on table `liked_post`
--
ALTER TABLE liked_post 
  ADD UNIQUE INDEX user_id(user_id);

--
-- Create index `music_id` on table `liked_post`
--
ALTER TABLE liked_post 
  ADD UNIQUE INDEX music_id(music_id);

--
-- Create table `comments`
--
CREATE TABLE comments (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user_id INT(11) DEFAULT NULL,
  music_id INT(11) DEFAULT NULL,
  date DATE DEFAULT NULL,
  comment VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create index `user_id` on table `comments`
--
ALTER TABLE comments 
  ADD UNIQUE INDEX user_id(user_id);

--
-- Create index `music_id` on table `comments`
--
ALTER TABLE comments 
  ADD UNIQUE INDEX music_id(music_id);

--
-- Create table `category`
--
CREATE TABLE category (
  id INT(11) NOT NULL AUTO_INCREMENT,
  category VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `artist`
--
CREATE TABLE artist (
  id INT(11) NOT NULL AUTO_INCREMENT,
  category_id INT(11) DEFAULT NULL,
  szuletese DATE DEFAULT NULL,
  `Élt ettől` INT(11) DEFAULT NULL,
  `Élt eddig` INT(11) DEFAULT NULL,
  leiras VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create index `category_id` on table `artist`
--
ALTER TABLE artist 
  ADD UNIQUE INDEX category_id(category_id);

-- 
-- Dumping data for table user
--
-- Table project.user does not contain any data (it is empty)

-- 
-- Dumping data for table uploaded_music
--
-- Table project.uploaded_music does not contain any data (it is empty)

-- 
-- Dumping data for table music
--
-- Table project.music does not contain any data (it is empty)

-- 
-- Dumping data for table liked_post
--
-- Table project.liked_post does not contain any data (it is empty)

-- 
-- Dumping data for table comments
--
-- Table project.comments does not contain any data (it is empty)

-- 
-- Dumping data for table category
--
-- Table project.category does not contain any data (it is empty)

-- 
-- Dumping data for table artist
--
-- Table project.artist does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;